#define INITIAL_BLOCK_HEIGHT 851500
#define INITIAL_LAST_PRICE 50000
#define DEFAULT_TX_POWER 0

#define DEFAULT_MEMPOOL_SECURE true
#define DEFAULT_LED_TEST_ON_POWER true
#define DEFAULT_LED_FLASH_ON_UPD false
#define DEFAULT_LED_BRIGHTNESS 128
#define DEFAULT_STEAL_FOCUS false
#define DEFAULT_MCAP_BIG_CHAR true
#define DEFAULT_MDNS_ENABLED true
#define DEFAULT_OTA_ENABLED true
#define DEFAULT_FETCH_EUR_PRICE false
#define DEFAULT_USE_SATS_SYMBOL false
#define DEFAULT_USE_BLOCK_COUNTDOWN true
#define DEFAULT_SUFFIX_PRICE false
#define DEFAULT_DISABLE_LEDS false
#define DEFAULT_DISABLE_FL false
#define DEFAULT_OWN_DATA_SOURCE true
#define DEFAULT_STAGING_SOURCE false
#define DEFAULT_V2_SOURCE_CURRENCY CURRENCY_USD


#define DEFAULT_TIME_OFFSET_SECONDS 3600

#define DEFAULT_HOSTNAME_PREFIX "btclock"
#define DEFAULT_MEMPOOL_INSTANCE "mempool.space"

#define DEFAULT_USE_NOSTR false
#define DEFAULT_NOSTR_NPUB "642317135fd4c4205323b9dea8af3270657e62d51dc31a657c0ec8aab31c6288"
#define DEFAULT_NOSTR_RELAY "wss://relay.primal.net"

#define DEFAULT_SECONDS_BETWEEN_PRICE_UPDATE 30
#define DEFAULT_MINUTES_FULL_REFRESH 60

#define DEFAULT_FG_COLOR GxEPD_WHITE
#define DEFAULT_BG_COLOR GxEPD_BLACK

#define DEFAULT_WP_TIMEOUT 15*60

#define DEFAULT_FL_MAX_BRIGHTNESS 2048
#define DEFAULT_FL_EFFECT_DELAY 15

#define DEFAULT_LUX_LIGHT_TOGGLE 128
#define DEFAULT_FL_ALWAYS_ON false
#define DEFAULT_FL_FLASH_ON_UPDATE false

#define DEFAULT_LED_STATUS false
#define DEFAULT_TIMER_ACTIVE true
#define DEFAULT_TIMER_SECONDS 1800
#define DEFAULT_CURRENT_SCREEN 0

#define DEFAULT_BITAXE_ENABLED false
#define DEFAULT_BITAXE_HOSTNAME "bitaxe1"

#define DEFAULT_ZAP_NOTIFY_ENABLED false
#define DEFAULT_ZAP_NOTIFY_PUBKEY "b5127a08cf33616274800a4387881a9f98e04b9c37116e92de5250498635c422"

#define DEFAULT_HTTP_AUTH_ENABLED false
#define DEFAULT_HTTP_AUTH_USERNAME "btclock"
#define DEFAULT_HTTP_AUTH_PASSWORD "satoshi"